language: java

jdk:
  - oraclejdk8

services:
  - mysql

install:
  - ./gradlew test --debug

notifications:
  email: ignatatassist@gmail.com

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS userbase;'