language: java
jdk:
  - oraclejdk8

service:
  - mysql

sudo:
  - true

before_install:
  - chmod +x gradlew

before_script:
  - mysql -e 'create database userbase'

install:
  - ./gradlew test --debug

